
/*account*/
export const  GET_ACTIVE_LIST = 'GET_ACTIVE_LIST'
export const GET_NOTICE_LIST = 'GET_NOTICE_LIST'
export const ADD_ACTIVE_LIST = 'ADD_ACTIVE_LIST'
export const ADD_NOTICE_LIST = 'ADD_NOTICE_LIST'
export const ADD_NOTICE_PAGE = 'ADD_NOTICE_PAGE'
export const ADD_ACTIVE_PAGE = 'ADD_ACTIVE_PAGE'
export const UPDATE_NEWS_DETAILS_STATUS = 'UPDATE_NEWS_DETAILS_STATUS'
export const UPDATE_NEWS_DETAILS_TEXT = 'UPDATE_NEWS_DETAILS_TEXT'
export const UPDATE_TRADE_CONF = 'UPDATE_TRADE_CONF'
// export const UPDATE_TRADE_CONF_ORDERBTN = 'UPDATE_TRADE_CONF_ORDERBTN'
export const UPDATE_TOTAL_ACCOUNT = 'UPDATE_TOTAL_ACCOUNT'
export const GET_TRADE_CONF = 'GET_TRADE_CONF'
// export const GET_TRADE_CONF_ORDERBTN = 'GET_TRADE_CONF_ORDERBTN'
export const GET_TOTAL_ACCOUNT = 'GET_TOTAL_ACCOUNT'

/*user*/
export const TEST_SSS = 'TEST_SSS'
export const UPDATE_TEST_SSS = 'UPDATE_TEST_SSS'

/*bank*/
export const GET_USER_BANK = 'GET_USER_BANK'
export const USER_BANK_DATA = 'USER_BANK_DATA'
export const CHANGE_BANK = 'CHANGE_BANK'
export const CHANGE_CARD = 'CHANGE_CARD'
export const CHANGE_CARD_TWO = 'CHANGE_CARD_TWO'
export const CHANGE_ADDR = 'CHANGE_ADDR'

/*risk*/
export const ISANSWER = 'ISANSWER'
